#!/usr/bin/env ruby

path = ENV['HOME'] + '/.mantou_earth'
puts path

IO.popen("#{path}/scrp/main") { |f| 
  name = f.gets
  puts name
  if name != "404"
    system "cd #{path} && rm `ls *.jpg | grep -v '#{name.split('/').last}'`"
    system "cd #{path}/scrp && osascript earth.scpt"
  end
}
